CREATE DATABASE IF NOT EXISTS drivemitra;
USE drivemitra;

CREATE TABLE IF NOT EXISTS drivers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  vehicle_number VARCHAR(50) NOT NULL UNIQUE,
  mobile VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slip_id VARCHAR(50) NOT NULL UNIQUE,
  driver_name VARCHAR(100) NOT NULL,
  vehicle_number VARCHAR(50) NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  item_type VARCHAR(100) NOT NULL,
  quantity INT NOT NULL,
  location VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slip_id VARCHAR(50) NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  customer_location VARCHAR(255) NOT NULL,
  driver_name VARCHAR(100) NOT NULL,
  item_type VARCHAR(100) NOT NULL,
  quantity INT NOT NULL,
  rating INT NOT NULL,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS traffic_updates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  route_name VARCHAR(150) NOT NULL,
  status VARCHAR(50) NOT NULL,
  reported_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
